# Generated by Django 5.2.1 on 2025-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_jenis_barang_waktu_post_barang_jenis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
