# Generated by Django 5.2.1 on 2025-07-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_about_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('subjudul', models.CharField(default='Subjudul', max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
        ),
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='portofolio/')),
                ('link_sumber', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='isi',
            new_name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
        migrations.RemoveField(
            model_name='about',
            name='img2',
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='judul',
            field=models.CharField(max_length=100),
        ),
    ]
