# Generated by Django 5.2.1 on 2025-07-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_hero_portofolio_rename_isi_about_deskripsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: HTML5, Python, Django', max_length=50)),
                ('ikon', models.ImageField(upload_to='skills/')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='skills',
            field=models.ManyToManyField(blank=True, to='profil.skill'),
        ),
    ]
