# Generated by Django 5.2.1 on 2025-07-07 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_skill_about_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='judul',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='deskripsi',
            new_name='tagline',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='subjudul',
        ),
        migrations.AddField(
            model_name='hero',
            name='foto_profil',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hero/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='jabatan',
            field=models.CharField(default=django.utils.timezone.now, help_text='Contoh: Lecturer & Content Creator', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='salam_pembuka',
            field=models.CharField(default='Halo Semua 👋, saya', max_length=100),
        ),
    ]
