# Generated by Django 5.2.1 on 2025-07-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_rename_jabatan_hero_profesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='clients/')),
            ],
        ),
    ]
