# Generated by Django 5.2.1 on 2025-07-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
